services:
  postgres:
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_PASSWORD: innovatinsa-piwio-5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
