-- Run this from dbeaber to create 1 database per student / group
CREATE DATABASE group01;
CREATE DATABASE group02;
CREATE DATABASE group03;
CREATE DATABASE group04;
CREATE DATABASE group05;
CREATE DATABASE group06;
CREATE DATABASE group07;
CREATE DATABASE group08;
CREATE DATABASE group09;
CREATE DATABASE group10;
CREATE DATABASE group11;
CREATE DATABASE group12;
CREATE DATABASE group13;
CREATE DATABASE group14;
CREATE DATABASE group15;